apiVersion: v1
kind: Pod
metadata:
  name: folio-debug
spec:
  containers:
  - name: folio-debug
    image: ghcr.io/culibraries/folio_debug:latest
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - "3600"
    envFrom:
      - secretRef:
          name: db-connect-modules
      # - secretRef:
      #     name: kafka-connect
  restartPolicy: Always
