apiVersion: v1
kind: Pod
metadata:
  name: folio-debug
  namespace: default
spec:
  containers:
  - name: folio-debug
    image: ghcr.io/culibraries/folio_debug:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
